gem 'pry'
gem 'rails',  '3.0.20.11'
gem 'awesome_print', '1.0.2'
gem 'zeus'
gem 'debugger'
gem 'ruby-debug'
gem 'debuegger-linecache'
gem 'erubis'
gem 'multi_json'
gem 'net-ssp'
gem 'net-scp'
gem 'pry-debugger'
gem 'rake',  '0.9.2.2'
gem 'rdoc'
gem 'debugger-ruby-core-source'
gem 'ruby-core-source'
gem 'rvm'
